export const yaku = {
    <div>
        <p>1飜役</p>
        <button>立直</button>
        <button>一発</button>
        <button>面前清自摸和</button>
        <button>白</button>
        <button>発</button>
        <button>中</button>
        <button>自風牌</button>
        <button>場風牌</button>
        <button>タンヤオ</button>
        <button>平和</button>
        <button>一盃口</button>
        <button>海底撈月</button>
        <button>河底撈魚</button>
        <button>嶺上開花</button>
        <button>槍槓</button>
        <button>ドラ</button>
      </div>
      <div>
        <p>2飜役</p>
        <button>ダブル立直</button>
        <button>三色同順</button>
        <button>三色同刻</button>
        <button>三暗刻</button>
        <button>一気通貫</button>
        <button>チャンタ</button>
        <button>七対子</button>
        <button>対々和</button>
        <button>三槓子</button>
        <button>小三元</button>
        <button>混老頭</button>
      </div>
      <div>
        <p>3飜役</p>
        <button>二盃口</button>
        <button>純チャン</button>
        <button>混一色</button>
      </div>
      <div>
        <p>5飜役</p>
        <button>流し満貫</button>
      </div>
      <div>
        <p>6飜役</p>
        <button>清一色</button>
      </div>
      <div>
        <p>役満</p>
        <button>天和</button>
        <button>地和</button>
        <button>人和</button>
        <button>四暗刻</button>
        <button>国士無双</button>
        <button>大三元</button>
        <button>緑一色</button>
        <button>小四喜</button>
        <button>字一色</button>
        <button>清老頭</button>
        <button>四槓子</button>
        <button>九蓮宝燈</button>
      </div>
      <div>
        <p>ダブル役満</p>
        <button>四暗刻単騎</button>
        <button>大四喜</button>
        <button>純正九蓮宝燈</button>
        <button>国士無双十三面待ち</button>
      </div>
}